# Generated by Django 4.2.5 on 2023-09-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero1', models.IntegerField()),
                ('numero2', models.IntegerField()),
                ('operacion', models.CharField(choices=[('suma', 'Suma'), ('resta', 'Resta'), ('multiplicacion', 'Multiplicación')], max_length=15)),
            ],
        ),
    ]
